export const API = {
  signin: "/admin/login",
  sendForgotPasswordOtp: "/admin/forgot-password/send-otp",
  verifyForgotPasswordOtp: "/admin/forgot-password/verify-otp",
  resetPassword: "/admin/forgot-password/update-password",
  changePassword: "/admin/account-settings/change-password",
  getDashbaoardData: "/admin/dashboard",
  editAdminProfile: "/admin/update",
  getCountryList: "/common/country-list",
  getStateList: "/common/state-list",
  getCityList: "/common/city-list",
  adminDetails: "/admin",

  getConfigs: "/common/config",
  // User APIs
  getUsersList: "/admin/get-user-list",
  getUserFollowerList: "/admin/get-user-follower-list",
  getUserFollowingList: "/admin/get-user-following-list",
  getUsersDetails: "/admin/get-user-profile",
  getReportedUsersList: "/admin/get-reported-users",
  getAppDownloadLink: "/qr-download",
  exportUsersCSV: "/user/export-users",
  getUserBussinessList: "/admin/user/businesses",

  // Products
  productsList: "/admin/products",
  createProduct: "/admin/products",
  editProduct: (id: number) => `/admin/products/${id}`,

  getReportedUserDetails: (id: number) => `/admin/get-reported-user/${id}`,
  updateReportedUserStatus: "/admin/update-user-report-status",
  updateUserDetails: "/admin/update-user-profile",
  changeUserStatus: "/admin/update-status",
  changePostStatus: "/admin/update-post-status",
  addRemovePoints: "/admin/add-points",
  addRemoveBadge: "/admin/add-badges",
  changeReportedPostStatus: "/admin/update-report-status",
  deleteUserPost: (id: number) => `/admin/delete-user-post/${id}`,
  deleteUser: "/admin/delete-user",
  getSubCategopryDetails: (id: number) => `/subCategory/${id}`,
  createCategory: "/admin/add-sub-category",
  getCategory: "/admin/get-sub-category-list",
  getCategoryById: "/admin/get-sub-category-by-id",
  updateCategory: "/admin/update-sub-category",
  deleteCategory: "/admin/delete-sub-category",
  changeCategoryStatus: "/admin/change-sub-category-status",

  createAdventurePost: "/admin/add-post",
  updateAdventurePost: "/admin/update-post",
  getAdventurePostList: "/admin/get-post-list",
  getUsersPostList: "/admin//get-user-posts",
  getUserReportedPostList: "/admin/get-reported-posts",
  getUserReportedPostDetails: (id: number) => `/admin/get-reported-post/${id}`,
  getUsersPostCommentList: "/admin/get-user-post-comment",
  getUserPostDetails: "/admin/get-user-post-details",
  getAdventurePost: "/admin/get-post-by-id",
  deleteAdventure: "/admin/delete-post",
  changeAdventureStatus: "/admin/change-post-status",
  changeAdventureOrder: "/admin/swap-order",
  changeSubCategoryOrder: "/admin/swap-order-category",

  getGroupsList: "/admin/group/list",
  getGroupPosts: "/admin/group/post/list",
  getGroupLeaderboard: "/admin/group/leaderboard",
  deleteGroup: "/admin/group/delete",
  sendNotification: "/admin/send-notification",
  listNotification: "/admin/list-notification",
  deleteNotification: (id: number) => `/admin/delete-notification/${id}`,
  createDeleteBadge: "/admin/trophies",
  listBadges: "/admin/trophies/list",
  updateBadge: (id: number) => `/admin/trophies/${id}`,
  updateBadgeStatus: (id: number) => `/admin/trophies/status/${id}`,
  universitiesList: "/admin/university/list",
  createUniversity: "/admin/university",
  universityLeaderboard: "/admin/university/leaderboard",
  universityEditOrDelete: (id: number) => `/admin/university/${id}`,
  changeUniversityStatus: (id: number) => `/admin/university/status/${id}`,
  getUniversityStateList: "/university/states",
  removeUserFromUniversity: "/admin/university/remove",
  createAnnoucementsPost: "/admin/announcement",
  editDeleteAnnoucementsPost: (id: number) => `/admin/announcement/${id}`,
  checkVideostatus: "/user/post/check-video-status",

  // Contest APIs
  createContest: "/admin/contest/create-contest",
  getContestList: "/admin/contest/contest-list",
  editContest: "/admin/contest/edit-contest",
  getContestDetails: (id: number) => `/admin/contest/view-contest/${id}`,
  deleteContest: (id: number) => `/admin/contest/delete-contest/${id}`,
  changeContestStatus: (id: number) => `/admin/contest/status/${id}`,
  toggelContestSettings: (id: number) => `/admin/contest/toggle-settings/${id}`,
  listContestUserPost: `/admin/contest/user-post-list`,
  getContestLeaderboard: "/admin/contest/leaderboard",
  listContestantsLists: "/admin/contest/contestant-list",
  listBoosterList: "/admin/contest/contestant-booster-list",
  changeContestUserPostStatus: (id: number) =>
    `/admin/contest/post/status/${id}`,
  getContestUserPostDetails: "/admin/contest/post-details",
  getContestUserPostComments: "/admin/contest/comment/list",

  // Charity APIs
  listCharities: "/admin/contest/charity-list",
  createCharity: "/admin/contest/create-charity",
  editCharity: "/admin/contest/edit-charity",
  changeCharityStatus: (id: number) => `/admin/contest/charity/status/${id}`,
  deleteCharity: (id: number) => `/admin/contest/delete-charity/${id}`,

  //Business APIs
  listBusinesses: "/admin/business/list",
  listRewardAdventures: "/admin/business/reward-adventure",
  chnageBusinessStatus: "/admin/business/status",
  getBusinessSizesList: "/v3/business/business-sizes",
  getBusinessIndustryList: "/v3/business/industries",
  getRewardAdventureDropdownData: "/admin/business/reward-adventure/dropdown",
  editBusiness: "/admin/business",
  listRewards: "/admin/business/rewards",
  changeRewardAdventureStatus: (id: number) =>
    `/admin/business/reward-adventures/${id}/status`,
  verifyBusiness: (businessId: number) =>
    `/admin/business/${businessId}/verify`,
  getBusinessDetails: (businessId: number) => `/admin/business/${businessId}`,
  getRewardAdventureDetails: (businessId: number) =>
    `/admin/business/reward-adventure/${businessId}`,
  exportBusinessAccountsCSV: "/user/export-businesses",
  exportRewardLogsCSV: "/user/export-rewards",
  monthlyOnlineOrdersDropdown: "/common/monthly-online-orders",
  physicalLocationsRangeDropdown: "/common/physical-locations-range",
  estimatedAnnualRevenueDropdown: "/common/estimated-annual-revenue",
  getBusinessSubscriptionList: "/admin/subscription",
  getBusinessSubscriptionDetails: (id: number) => `/admin/subscription/${id}`,
  getInvoicesList: "/admin/subscription/invoices",

  //posts APIs
  updateGlobalPostsConfig: "/admin/update-global-post-points",

  // Tags APIs
  getTagsList: "/admin/tag-list",
  createTag: "/admin/tag",
  editTag: (id: number) => `/admin/tag/${id}`,
  deleteTag: (id: number) => `/admin/tag/${id}`,
};
